apiVersion: v2
appVersion: 2.0.3
dependencies:
- name: vcverifier
  repository: https://i4trust.github.io/helm-charts
  version: 1.0.9
description: Chart holder for argo-cd
name: verifier
type: application
version: 1.0.9
