
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallet-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: wallet.tango.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wallet-service
                port:
                  number: {{ .Values.commonEnvVars.WALLET_PORT_HTTPS }}
  tls:
    - hosts:
        - wallet.tango.io
      secretName: wallet-cert
