
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallet-ingress
spec:
  rules:
    - host: wallet.tango.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wallet-service
                port:
                  number: 443
  tls:
    - hosts:
        - wallet.tango.io
      secretName: wallet-cert
