
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app.kubernetes.io/name: {{ include "wallet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: wallet
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.commonEnvVars.WALLET_PORT_HTTP }}
      targetPort: {{ .Values.commonEnvVars.WALLET_PORT_HTTP }}
  selector:
    app.kubernetes.io/name: {{ include "wallet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: wallet
