
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app.kubernetes.io/name: {{ include "wallet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: wallet
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.commonEnvVars.WALLET_PORT_HTTPS }}
  selector:
    app.kubernetes.io/name: {{ include "wallet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: wallet

