replicaCount: 1
revisionHistoryLimit: 10
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

image:
  repository: pablomarrtinez/wallet
  tag: v4.1.4
  pullPolicy: IfNotPresent

## Variables de entorno comunes a todos los contenedores
commonEnvVars:
  ISSUER_PORT_HTTP: 32100
  ISSUER_PORT_HTTPS: 32000
  VERIFIER_PORT_HTTP: 32101
  VERIFIER_PORT_HTTPS: 32001
  WALLET_PORT_HTTP: 32102
  WALLET_PORT_HTTPS: 32002
  MODE: "Default"
  LOCAL: "true"
  PEER_ENDPOINT: "peer0.org1.example.com"

verifierUmu:
  deploymentEnabled: true
  name: verifierUmu
  args: >
    keytool -importcert -file /etc/tls/tls.crt -alias tls -keystore /opt/java/openjdk/lib/security/cacerts -storepass changeit -noprompt && /app/ssikit.sh verifier
  envVars:
    - name: URI_VERIFIER
      value: "ssikit-verifier"
  ports:
    - 32101
    - 32001

  ## Montaje de volúmenes
  volumeMounts:
    - name: tls-cert
      mountPath: "/etc/tls"
      readOnly: true

  volumes:
    - name: tls-cert
      secret:
        secretName: verifier-cert

## Etiquetas y anotaciones adicionales (opcional)
additionalLabels: {}
additionalAnnotations: {}

## Configuraciones adicionales (opcional)
serviceAccount:
  create: false
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  annotations: {}
