replicaCount: 1
revisionHistoryLimit: 10
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

image:
  repository: pablomarrtinez/wallet
  tag: v4.1.4
  pullPolicy: IfNotPresent

## Variables de entorno comunes a todos los contenedores
commonEnvVars:
  ISSUER_PORT_HTTP: 32100
  ISSUER_PORT_HTTPS: 32000
  VERIFIER_PORT_HTTP: 32101
  VERIFIER_PORT_HTTPS: 32001
  WALLET_PORT_HTTP: 32102
  WALLET_PORT_HTTPS: 32002
  MODE: "Default"
  LOCAL: "true"
  PEER_ENDPOINT: "peer0.org1.example.com"

issuer:
  deploymentEnabled: true
  name: issuer
  args: >
    keytool -importcert -file /etc/issuer-tls/tls.crt -alias issuer-tls -keystore /opt/java/openjdk/lib/security/cacerts -storepass changeit -noprompt && 
    keytool -importcert -file /etc/wallet-tls/tls.crt -alias wallet-tls -keystore /opt/java/openjdk/lib/security/cacerts -storepass changeit -noprompt && 
    keytool -importcert -file /etc/verifier-tls/tls.crt -alias verifier-tls -keystore /opt/java/openjdk/lib/security/cacerts -storepass changeit -noprompt && 
    /app/ssikit.sh issuer

  envVars:
    - name: URI_ISSUER
      value: "ssikit-issuer"
  ports:
    - 32100
    - 32000

  ## Montaje de volúmenes
  volumeMounts:
    - name: issuer-cert
      mountPath: "/etc/issuer-tls"
      readOnly: true
    - name: wallet-cert
      mountPath: "/etc/wallet-tls"
      readOnly: true
    - name: verifier-cert
      mountPath: "/etc/verifier-tls"
      readOnly: true

  volumes:
    - name: issuer-cert
      secret:
        secretName: issuer-cert
    - name: wallet-cert
      secret:
        secretName: wallet-cert
    - name: verifier-cert
      secret:
        secretName: verifier-cert

## Etiquetas y anotaciones adicionales (opcional)
additionalLabels: {}
additionalAnnotations: {}

## Configuraciones adicionales (opcional)
serviceAccount:
  create: false
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  annotations: {}
