apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "issuer.fullname" . }}
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
    component: issuer

    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- with .Values.updateStrategy }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "issuer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: issuer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "issuer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: issuer
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: issuer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - {{ .Values.issuer.args | quote }}
          env:
            {{- range $key, $value := .Values.commonEnvVars }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- range $envVar := .Values.issuer.envVars }}
            - name: {{ $envVar.name }}
              value: "{{ $envVar.value }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.commonEnvVars.ISSUER_PORT_HTTP }}
              name: issuer-http
            - containerPort: {{ .Values.commonEnvVars.ISSUER_PORT_HTTPS }}
              name: issuer-https
          volumeMounts:
            {{- range $mount := .Values.volumeMounts }}
            - name: {{ $mount.name }}
              mountPath: "{{ $mount.mountPath }}"
              {{- if $mount.readOnly }}
              readOnly: {{ $mount.readOnly }}
              {{- end }}
            {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}

