
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: issuer-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: issuer.tango.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: issuer-service
                port:
                  number: {{ .Values.commonEnvVars.ISSUER_PORT_HTTPS }}
  tls:
    - hosts:
        - issuer.tango.io
      secretName: issuer-cert
