{{- if .Values.issuer.deploymentEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: issuer-service
  labels:
    app.kubernetes.io/name: {{ include "issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: issuer
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.commonEnvVars.ISSUER_PORT_HTTPS }}
  selector:
    app.kubernetes.io/name: {{ include "issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: issuer
{{- end }}
