
apiVersion: v1
kind: Service
metadata:
  name: issuer-service
  labels:
    app.kubernetes.io/name: {{ include "issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: issuer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.commonEnvVars.ISSUER_PORT_HTTP }}
      targetPort: {{ .Values.commonEnvVars.ISSUER_PORT_HTTP }}
  selector:
    app.kubernetes.io/name: {{ include "issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: issuer
