apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peppdp-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2 
spec:
  rules:
    - host: pep-pdp.tango.io
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: peppdp-service
                port:
                  number: 80
