
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verifierumu-ingress
spec:
  rules:
    - host: verifier.tango.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verifierumu-service
                port:
                  number: {{ .Values.commonEnvVars.VERIFIER_PORT_HTTP }}
  tls:
    - hosts:
        - verifier.tango.io
      secretName: verifier-cert
