
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verifierUmu-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: verifier.tango.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verifierUmu-service
                port:
                  number: 443
  tls:
    - hosts:
        - verifier.tango.io
      secretName: verifier-cert
