
apiVersion: v1
kind: Service
metadata:
  name: verifierumu-service
  labels:
    app.kubernetes.io/name: {{ include "verifierumu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: verifierumu
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.commonEnvVars.VERIFIER_PORT_HTTPS }}
  selector:
    app.kubernetes.io/name: {{ include "verifierumu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: verifierumu
